#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/medical_app?useSSL=false&serverTimezone=UTC
#    username: root
#    password: Ss3141592653517
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
  # jpa:
  #   hibernate:
  #     ddl-auto: validate
  #   properties:
  #     hibernate.default_schema: ${POSTGRES_SCHEMA:pins}
  # liquibase:
  #   default-schema: ${POSTGRES_SCHEMA:pins}
  #   change-log: classpath:/${POSTGRES_SCHEMA:pins}/master.yml

#bot:
#  name: "aitherapist_bot"
#  token: "8038842126:AAFlDr1ivAbzlRnr_uUgZ8m4qkm6zOiYFlY"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical_app?useSSL=false&serverTimezone=UTC
    username: root
    password: Ss3141592653517
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  liquibase:
    enabled: false

bot:
  name: "aitherapist_bot"
  token: "8038842126:AAFlDr1ivAbzlRnr_uUgZ8m4qkm6zOiYFlY"