spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical_app?useSSL=false&serverTimezone=UTC
    username: root
    password: Ss3141592653517
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

bot:
  name: "aitherapist_bot"
  token: "8038842126:AAFlDr1ivAbzlRnr_uUgZ8m4qkm6zOiYFlY"
