spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical_app?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  liquibase:
    enabled: false

bot:
  name: "aitherapist_bot"
  token: "8038842126:AAFlDr1ivAbzlRnr_uUgZ8m4qkm6zOiYFlY"
